language: python
python:
  - "3.7"
dist: bionic     # https://docs.travis-ci.com/user/languages/python/#python-37-and-higher
install:
  - travis_retry pip install -r requirements.txt
script: make html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: build/html
  fqdn: slimta.org
