language: python
python:
  - "3.7"
dist: xenial     # https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
install:
  - travis_retry pip install -r requirements.txt
script: make html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: build/html
  fqdn: slimta.org
